[project]
name = "django-pre-commit"
version = "0.1.0"
description = "pre-commmit hooks for Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django",
]

[project.scripts]
compile-messages = "hooks.compile_messages:main"